name: Daily Request

on:
  schedule:
    - cron: '30 0 * * *'  # Run daily at 00:30
  workflow_dispatch:  # Allow manual triggering
    inputs:
      mb_id:
        description: 'mb_id value'
        required: false
        default: ${{ secrets.MB_ID }}  # Access the MB_ID secret
      mb_password:
        description: 'mb_password value'
        required: false
        default: ${{ secrets.MB_PASSWORD }}  # Access the MB_PASSWORD secret

jobs:
  send_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Send POST Request
        env:
          MB_ID: ${{ github.event.inputs.mb_id }}
          MB_PASSWORD: ${{ github.event.inputs.mb_password }}
        run: |
          curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "Origin: https://nowhosting.kr" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" \
            -H "Referer: https://nowhosting.kr/bbs/login.php" \
            -d "mb_id=${MB_ID}&mb_password=${MB_PASSWORD}" \
            https://nowhosting.kr/bbs/login_check.php
